"""delete created_at updated_at

Revision ID: 48887086754d
Revises: c65f912c943a
Create Date: 2025-11-16 17:54:50.356617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48887086754d'
down_revision: Union[str, Sequence[str], None] = 'c65f912c943a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_primary_tokens_created_at'), table_name='primary_tokens')
    op.drop_index(op.f('ix_primary_tokens_updated_at'), table_name='primary_tokens')
    op.drop_column('primary_tokens', 'updated_at')
    op.drop_column('primary_tokens', 'created_at')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('UTC'::text, now())"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('UTC'::text, now())"), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.add_column('primary_tokens', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('UTC'::text, CURRENT_TIMESTAMP)"), autoincrement=False, nullable=False))
    op.add_column('primary_tokens', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('UTC'::text, CURRENT_TIMESTAMP)"), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_primary_tokens_updated_at'), 'primary_tokens', ['updated_at'], unique=False)
    op.create_index(op.f('ix_primary_tokens_created_at'), 'primary_tokens', ['created_at'], unique=False)
    # ### end Alembic commands ###
