"""add_primary_key

Revision ID: c65f912c943a
Revises: fc1fae57b054
Create Date: 2025-11-05 16:42:13.157753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c65f912c943a'
down_revision: Union[str, Sequence[str], None] = 'fc1fae57b054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('primary_tokens',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', CURRENT_TIMESTAMP)"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("timezone('UTC', CURRENT_TIMESTAMP)"),
                              nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_primary_tokens_created_at'), 'primary_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_primary_tokens_token'), 'primary_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_primary_tokens_updated_at'), 'primary_tokens', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_primary_tokens_updated_at'), table_name='primary_tokens')
    op.drop_index(op.f('ix_primary_tokens_token'), table_name='primary_tokens')
    op.drop_index(op.f('ix_primary_tokens_created_at'), table_name='primary_tokens')
    op.drop_table('primary_tokens')
    # ### end Alembic commands ###
